// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdrzqxoupoqpfmumvwrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcnpxeG91cG9xcGZtdW12d3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDc3ODgsImV4cCI6MjA2MTQyMzc4OH0.H6Qv0Feu6beTrwaK_ZMENIeEsTfD6X6POKYXb5rH2Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);